# -*- coding: utf-8 -*-
"""Simple ETL Pipeline: Extraction, Transformation, and Loading.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tqy-8ydKn_zcBC0IhX-vbFJ8IZMEdmrw
"""

# Import libraries
import pandas as pd
import numpy as np

!pip install kaggle  #Install the Kaggle library

#Allows you to upload files from your local computer to the Colab environment
from google.colab import files

files.upload()

# Change permissions for greater security
!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

#List the dataset files to verify that the CSV is available
!kaggle datasets files -d  pavantanniru/-datacleaningforbeginnerusingpandas

#Download only the CSV file, without downloading a ZIP
!kaggle datasets download -d pavantanniru/-datacleaningforbeginnerusingpandas --file Data-cleaning-for-beginners-using-pandas.csv

#Load the CSV file into a Pandas DataFrame:
df = pd.read_csv("Data-cleaning-for-beginners-using-pandas.csv")

df.head(5)

#We will check how many null values each column has using the function below.
df.isnull().sum()

# Replace all occurrences of -1 in the 'Established' column with NaN (Not a Number) or null values to indicate missing or invalid data.
df["Established"] = df["Established"].replace(-1,np.nan)
df.head(10)

#Drop all rows that have the null values in all columns
df=df.dropna()
df.head(10)

#We will check again how many null values each column has using the function below.
df.isnull().sum()

'''We changed the lines of code for a function'''
# Since the 'Salary' column contains characters like '$' and 'k', we need to remove these characters to convert the column to numeric values.
def clean_1(x):
    x=x.replace("$",'')
    x=x.replace("k",'')
    return x

df['Salary'] = df['Salary'].apply(clean_1)
df.head()

'''We changed the for statement to a function that allows us to create a reusable block of code.'''
#Convert the string into float by getting the average
def average_of_this_two(args):
    try :
        return float(args)
    except:
        values = args.split('-')
        if len(values) == 2:
            return float(int(values[0]) + int(values[1]) ) /2

df['Salary'] = df["Salary"].apply(average_of_this_two)
df.head(5)

'''We change the for statement to a function'''
# Clean the location column
def clean_location(location):
    # Split on spaces
    parts = location.split(',')

    # If there are exactly 2 parts (e.g., "New York"), combine them
    if len(parts) == 2:
        return parts[0]
    else:
        return location.split(' ')[0]

# Apply the function to the 'location' column
df['Location'] = df['Location'].apply(clean_location)
df.head()

#Convert all -1 to FALSE
df['Easy Apply']=df["Easy Apply"].replace("-1","FALSE")
df

# Remove rows from the DataFrame where the 'Rating' column has a value of -1.0
df = df[df['Rating'] != -1.0]
df = df.reset_index(drop=True)
df

#Saving data to an SQL database
import sqlite3
# Connect to the database (or create it if it doesn't exist)
connection = sqlite3.connect('my_dbs.sqlite')
df.to_sql('dataset_1', connection, if_exists='replace', index=False)
connection.close()

# Connect to the database
connection = sqlite3.connect('my_dbs.sqlite')
# Read data from the table
df_leido = pd.read_sql('SELECT * FROM dataset_1', connection)
# Display data
print(df_leido)
# Close the coonnection
connection.close()